export const data = [
  {
    title: "Nykaa",
    repo: "https://github.com/sarangKaliyath/U2_Clone",
    website: "https://u2ubk.netlify.app/homepage",
    project_thumbnail: "/home_page.png",
    txt1: "Clone of a Popular E-commerce Website that sells beauty,wellness, and fashion products.",
    tech: "Tech: JS, HTML and, CSS.",
  },
  {
    title: "Nykaa V2.0",
    repo: "https://github.com/sarangKaliyath/U3_V3.0",
    website: "https://u3-ubk.herokuapp.com/",
    project_thumbnail: "/home_page.png",
    txt1: "This is the predecessor of the the Nykaa website built with a distinct tech-stack.",
    tech: "Tech: Express, MongoDB, Node.js and, EJS.",
  },
  {
    title: "Star Wars",
    repo: "https://github.com/sarangKaliyath/star_wars_api/tree/master/starWars",
    website: "https://star-wars-black.vercel.app/",
    project_thumbnail: "/placeholder.png",
    txt1: "A self designed project inspired by characters of Star Wars franchise.",
    tech: "Tech: JS, HTML and, CSS.",
  },
  {
    title: "Tumblr",
    repo: "https://github.com/sarangKaliyath/Tumblr_clone",
    website: "https://laughing-edison-2847b1.netlify.app/",
    project_thumbnail: "/tumblr_home.png",
    txt1: "Clone of American micro-blogging and social networking website.",
    tech: "Tech: JS, React, Express, MongoDB.",
  },
  {
    title: "Easy-Delivery",
    repo: "https://github.com/piyushrana00456/Easy-delivery",
    website: "https://easy-delivery.netlify.app/",
    project_thumbnail: "/easy_delivery_home.png",
    txt1: "Hackathon Project focused towards assisting Logistics and Operations.",
    tech: "Tech:JS, React, Express, MongoDB, WebSockets.",
  },
];
